apiVersion: apps/v1
kind: Deployment
metadata:
  name: gloogatewaytst-deployment
spec:
  selector:
    matchLabels:
      app: gloogatewaytst
  template:
    metadata:
      labels:
        app: gloogatewaytst
    spec:
      containers:
        - name: gloogatewaytst
          image: ordercontainerregistry.azurecr.io/gloogatewaytst:1.0.4
          ports:
            - containerPort: 5002
          env:
            - name: AuthConf__Url
              value: http://13.64.130.251/identitymgmt/realms/AucRealm      
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
            requests:
              memory: "128Mi"
              cpu: "150m"
      restartPolicy: Always
  

