apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: gloogatewaytst-virtualservice
  namespace: dev
spec:
  virtualHost:
    domains:
      - "*"
    routes:
      - matchers:
          - prefix: /gloogatewaytst/
        routeAction:
          single:
            upstream:
              name: gloogatewaytst-upstream
              namespace: dev
        options:
          prefixRewrite: "/"

      - matchers:
          - prefix: /identitymgmt/
        routeAction:
          single:
            upstream:
              name: keycloak-upstream
              namespace: dev
        options:
          prefixRewrite: "/identitymgmt/"

---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: gloogatewaytst-upstream
  namespace: dev
spec:
  kube:
    serviceName: gloogatewaytst-service
    serviceNamespace: dev
    servicePort: 80

---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: keycloak-upstream
  namespace: dev
spec:
  kube:
    serviceName: keycloak-service
    serviceNamespace: dev
    servicePort: 80
